// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMXTC4QoX65YKBFNbe0YAZJdxUBCkxhK0',
    appId: '1:230880342750:android:98357ec5d5953e9c74484f',
    messagingSenderId: '230880342750',
    projectId: 'mynotes-first-pr',
    storageBucket: 'mynotes-first-pr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQlf6H5oU-RWSCsc2zgY4_dUWLXzQIvSQ',
    appId: '1:230880342750:ios:e17396df2bea1bdd74484f',
    messagingSenderId: '230880342750',
    projectId: 'mynotes-first-pr',
    storageBucket: 'mynotes-first-pr.appspot.com',
    iosClientId: '230880342750-j2sn11354j405s3807st2a0tjt1gja22.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginApp',
  );
}
